/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as IndexRouteImport } from './routes/index'

const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grants': typeof GrantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/grants': typeof GrantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grants': typeof GrantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/grants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/grants'
  id: '__root__' | '/' | '/grants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GrantsRoute: typeof GrantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GrantsRoute: GrantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
